on:
  push:
    branches:
      - master

name: Deploy master branch
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install virtualenv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
      - name: Test
        run: |
          virtualenv env-test
          source env-test/bin/activate
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          nosetests test

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Npm install
        uses: actions/npm@master
        with:
          args: install
      - name: Serverless deploy
        uses: mirrorhanyu/serverless-github-action-python@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
